<>
  <h3 align="left">My stack and tools:</h3>
  <p align="left">
    <a
      href="https://reactjs.org/"
      target="_blank"
      rel="noreferrer"
      style="margin-right: 30px"
    >
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original-wordmark.svg"
        alt="React"
        width="30"
        height="30"
      />
    </a>
    <a
      href="https://redux.js.org"
      target="_blank"
      rel="noreferrer"
      style="margin-right: 30px;"
    >
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/redux/redux-original.svg"
        alt="Redux"
        width="30"
        height="30"
      />
    </a>
    <a
      href="https://nodejs.org/uk/"
      target="_blank"
      rel="noreferrer"
      style="margin-right: 30px;"
    >
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-plain.svg"
        alt="Node Js"
        width="30"
        height="30"
      />
    </a>
    <a
      href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
      target="_blank"
      rel="noreferrer"
      style="margin-right: 30px;"
    >
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-plain.svg"
        alt="JavaScript"
        width="30"
        height="30"
      />
    </a>
    <a href="https://webpack.js.org" target="_blank" rel="noreferrer">
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/webpack/webpack-original.svg"
        alt="WebPack"
        width="30"
        height="30"
      />
    </a>
    <a
      href="https://www.w3.org/html/"
      target="_blank"
      rel="noreferrer"
      style="margin-right: 30px;"
    >
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-plain-wordmark.svg"
        alt="HTML5"
        width="30"
        height="30"
      />
    </a>
    <a
      href="https://www.w3schools.com/css/"
      target="_blank"
      rel="noreferrer"
      style="margin-right: 30px;"
    >
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-plain-wordmark.svg"
        alt="CSS3"
        width="30"
        height="30"
      />
    </a>
    <a
      href="https://sass-lang.com"
      target="_blank"
      rel="noreferrer"
      margin="20"
    >
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sass/sass-original.svg"
        alt="SASS/SCSS"
        width="30"
        height="30"
        margin-right="40px"
      />
    </a>
    <a
      href="https://github.com/"
      target="_blank"
      rel="noreferrer"
      style="margin-right: 30px;"
    >
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg"
        alt="GitHub"
        width="30"
        height="30"
      />
    </a>
    <a
      href="https://code.visualstudio.com/"
      target="_blank"
      rel="noreferrer"
      style="margin-right: 20px;"
    >
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/vscode/vscode-original.svg"
        alt="VSCode"
        width="30"
        height="30"
      />
    </a>
    <a
      href="https://ubuntu.com/"
      target="_blank"
      rel="noreferrer"
      style="margin-right: 20px;"
    >
      <img
        src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/ubuntu/ubuntu-plain.svg"
        alt="Ubuntu"
        width="30"
        height="30"
      />
    </a>
  </p>
</>;
